# Example usage (with some repos from here): 
# ansible-playbook cloneReposAndSourceFiles.yml -e repos=["https://github.com/kenape/kubehelpers.git", "https://github.com/kenape/thercs.git"] -e source_files=["~/kubehelpers/helpers.sh", "~/thercs/bindings.sh"]
#
# This playbook clones repositories into the home directory and adds dynamic sourcing of files from them in .bashrc.

- name: Clone some repos and source files from them
  hosts: all
  become: yes

  vars:
    repos: "{{ repos | default([]) }}"
    source_files: "{{ source_files | default([]) }}"

  tasks:
    - name: Clone repositories
      git:
        repo: "{{ item }}"
        dest: "~/{{ item | basename }}"
      loop: "{{ repos }}"
      when: repos | length > 0

    - name: Add dynamic sourcing to .bashrc
      blockinfile:
        path: ~/.bashrc
        block: |
          
          # Check if shell is interactive in order to source things that would otherwise break scp, etc...
          if [[ $- == *i* ]]; then
          {% for file in source_files %}
            . {{ file }}
          {% endfor %}
          fi
      when: source_files | length > 0
